version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    tty: true
    stdin_open: true
    command: npm start
    volumes:
      - /app/node_modules
      - .:/app
    working_dir: /app
    restart: on-failure
    ports:
      - '8081:8081'